#!/bin/bash -ex
# we should always set proper ownership before exiting, otherwise
# the created packages will have root:root ownership and we'll be unable
# to delete them from our host.
trap 'chown -R --reference /build-inside/build-package /out/' EXIT

# the source directory is mounted read-only to prevent issues where the build
# could alter the source; we should copy it somewhere inside the container
cd /go/src/github.com/h2oai/steam
rsync -a /source/ .
make
make all linux

# Signing block. can be omitted if you don't need to sign your RPMs.
##gpg --import /tmp/private.key
##[[ $(gpg --list-secret-keys) =~ uid(.*) ]]
##KEYNAME="${BASH_REMATCH[1]}"
##[ -n "${KEYNAME}" ] || { echo "could not find key for signing purpose"; exit 1; }
##echo -e "%_gpg_name ${KEYNAME}\n%_signature gpg\n" > ${HOME}/.rpmmacros
# signing block end

# This is a standard fpm command. look at fpm's own help. The only thing that I like to do
# is installing all the things in a separate dir to prevent listing all the files - but it's
# just personal taste.
# don't forget to list all runtime dependencies for your package (i.e. all the shared libraries you link to!)
# the --rpmsign flag can be omitted if you don't need signing your package.
# the "setsid" magic is used to prevent rpmsign asking for a password.
cd /out
#echo -e "\n" | setsid fpm -t rpm -s dir -n mylua --rpm-sign --version ${VERSION} --description "my version of lua" --depends readline -C / /usr/local/lua
mkdir -p /go/src/github.com/h2oai/steam/dist/rpm/opt/steam/
cp -r /go/src/github.com/h2oai/steam/dist/steam-${STEAM_RELEASE_VERSION}-linux-amd64/ /go/src/github.com/h2oai/steam/dist/rpm/opt/steam/
echo -e "\n" | setsid fpm -t rpm -s dir -n steam --version ${STEAM_RELEASE_VERSION} --description "Steam Cluster Manager" --depends haproxy -C /go/src/github.com/h2oai/steam/dist/rpm/

#this would be the no-signature command line
# fpm -t rpm -s dir -n mylua --version ${VERSION} --description "my version of lua" --depends readline -C / /usr/local/lua
