/**
 * Created by justin on 7/21/16.
 */
import * as React from 'react';
import DefaultModal from '../../App/components/DefaultModal';
import '../styles/exportmodal.scss';

interface Props {
  name: string,
  open: boolean,
  onDownload: Function,
  onCancel: Function,
  modelId: number,
  projectId: number
}

export default class ExportModal extends React.Component<Props, any> {
  
  
  render(): React.ReactElement<DefaultModal> {
    return (
      <DefaultModal className="export-modal" open={this.props.open}>
        <header>
          EXPORT {this.props.name}
        </header>
        <section>
          <div>
            <span>FILE FORMAT</span>
          </div>
          <div>
            <form onSubmit={this.props.onDownload.bind(this)}>
              <fieldset>
                <input type="radio" value="java" name="downloadOption"/><label><span className="file-extension">.java</span><span>a POJO generated by H2O</span></label>
              </fieldset>
              <fieldset>
                <input type="radio" value="jar" name="downloadOption"/><label><span className="file-extension">.jar</span><span>a library file, can be used by java apps</span></label>
              </fieldset>
              <fieldset>
                <input type="radio" value="war" name="downloadOption"/><label><span className="file-extension">.war</span><span>a java-based web app, can be used by Jetty / Tomcat</span></label>
              </fieldset>
              <div className="actions">
                <div>Steam defaults to your browser default Downloads Folders</div>
                <button type="submit" className="default">Download</button>
                <button type="button" className="default invert" onClick={this.props.onCancel}>Cancel</button>
              </div>
            </form>
          </div>
        </section>
      </DefaultModal>
    );
  }
}
