/*

  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2016-05-05T14:33:37.823-07:00
  3.9.1.99999
  
  Standalone prediction code with sample test data for PCAModel named PCA_model_python_1462483981555_1

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://172.16.2.56:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://172.16.2.56:54321/3/Models.java/PCA_model_python_1462483981555_1 > PCA_model_python_1462483981555_1.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m PCA_model_python_1462483981555_1.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="PCA_model_python_1462483981555_1", algorithm="pca")
public class PCA_model_python_1462483981555_1 extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.DimReduction; }
  public boolean isSupervised() { return false; }
  public int nfeatures() { return 2; }
  public int nclasses() { return 2; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_PCA_model_python_1462483981555_1.VALUES;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* account_type */ PCA_model_python_1462483981555_1_ColInfo_0.VALUES,
    /* tbtw_skew */ null
  };

  public PCA_model_python_1462483981555_1() { super(NAMES,DOMAINS); }
  public String getUUID() { return Long.toString(7525277920015787644L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    java.util.Arrays.fill(preds,0);
    final int nstart = PCA_model_python_1462483981555_1_CATOFFS.VALUES[PCA_model_python_1462483981555_1_CATOFFS.VALUES.length-1];
    for(int i = 0; i < 2; i++) {
      for(int j = 0; j < 1; j++) {
        double d = data[PCA_model_python_1462483981555_1_PERMUTE.VALUES[j]];
        if(Double.isNaN(d)) continue;
        int last = PCA_model_python_1462483981555_1_CATOFFS.VALUES[j+1]-PCA_model_python_1462483981555_1_CATOFFS.VALUES[j]-1;
        int c = (int)d;
        if(c < 0 || c > last) continue;
        preds[i] += PCA_model_python_1462483981555_1_EIGVECS.VALUES[PCA_model_python_1462483981555_1_CATOFFS.VALUES[j]+c][i];
      }
      for(int j = 0; j < 1; j++) {
        preds[i] += (data[PCA_model_python_1462483981555_1_PERMUTE.VALUES[j+1]]-PCA_model_python_1462483981555_1_NORMSUB.VALUES[j])*PCA_model_python_1462483981555_1_NORMMUL.VALUES[j]*PCA_model_python_1462483981555_1_EIGVECS.VALUES[j+ nstart][i];
      }
    }
    return preds;
  }
}
// Standardization/Normalization scaling factor for numerical variables.
class PCA_model_python_1462483981555_1_NORMMUL implements java.io.Serializable {
  public static final double[] VALUES = new double[1];
  static {
    PCA_model_python_1462483981555_1_NORMMUL_0.fill(VALUES);
  }
  static final class PCA_model_python_1462483981555_1_NORMMUL_0 implements java.io.Serializable {
    static final void fill(double[] sa) {
      sa[0] = 5.58436824712467;
    }
  }
}
// Standardization/Normalization offset for numerical variables.
class PCA_model_python_1462483981555_1_NORMSUB implements java.io.Serializable {
  public static final double[] VALUES = new double[1];
  static {
    PCA_model_python_1462483981555_1_NORMSUB_0.fill(VALUES);
  }
  static final class PCA_model_python_1462483981555_1_NORMSUB_0 implements java.io.Serializable {
    static final void fill(double[] sa) {
      sa[0] = 0.1991126747518186;
    }
  }
}
// Categorical column offsets.
class PCA_model_python_1462483981555_1_CATOFFS implements java.io.Serializable {
  public static final int[] VALUES = new int[2];
  static {
    PCA_model_python_1462483981555_1_CATOFFS_0.fill(VALUES);
  }
  static final class PCA_model_python_1462483981555_1_CATOFFS_0 implements java.io.Serializable {
    static final void fill(int[] sa) {
      sa[0] = 0;
      sa[1] = 3;
    }
  }
}
// Permutation index vector.
class PCA_model_python_1462483981555_1_PERMUTE implements java.io.Serializable {
  public static final int[] VALUES = new int[2];
  static {
    PCA_model_python_1462483981555_1_PERMUTE_0.fill(VALUES);
  }
  static final class PCA_model_python_1462483981555_1_PERMUTE_0 implements java.io.Serializable {
    static final void fill(int[] sa) {
      sa[0] = 0;
      sa[1] = 1;
    }
  }
}
// Eigenvector matrix.
class PCA_model_python_1462483981555_1_EIGVECS implements java.io.Serializable {
  public static final double[][] VALUES = new double[4][];
  static {
    PCA_model_python_1462483981555_1_EIGVECS_0.fill(VALUES);
  }
  static class PCA_model_python_1462483981555_1_EIGVECS_0_0 implements java.io.Serializable {
    public static final double[] VALUES = new double[2];
    static {
      PCA_model_python_1462483981555_1_EIGVECS_0_0_0.fill(VALUES);
    }
    static final class PCA_model_python_1462483981555_1_EIGVECS_0_0_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = 0.0032243580559762133;
        sa[1] = -0.0013617137554073914;
      }
    }
}
  static class PCA_model_python_1462483981555_1_EIGVECS_0_1 implements java.io.Serializable {
    public static final double[] VALUES = new double[2];
    static {
      PCA_model_python_1462483981555_1_EIGVECS_0_1_0.fill(VALUES);
    }
    static final class PCA_model_python_1462483981555_1_EIGVECS_0_1_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = -0.37040045222543266;
        sa[1] = -0.9288721057828813;
      }
    }
}
  static class PCA_model_python_1462483981555_1_EIGVECS_0_2 implements java.io.Serializable {
    public static final double[] VALUES = new double[2];
    static {
      PCA_model_python_1462483981555_1_EIGVECS_0_2_0.fill(VALUES);
    }
    static final class PCA_model_python_1462483981555_1_EIGVECS_0_2_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = 0.014906848713457122;
        sa[1] = -0.006303117555796888;
      }
    }
}
  static class PCA_model_python_1462483981555_1_EIGVECS_0_3 implements java.io.Serializable {
    public static final double[] VALUES = new double[2];
    static {
      PCA_model_python_1462483981555_1_EIGVECS_0_3_0.fill(VALUES);
    }
    static final class PCA_model_python_1462483981555_1_EIGVECS_0_3_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = -0.9287469485106025;
        sa[1] = 0.37034447146299065;
      }
    }
}
  static final class PCA_model_python_1462483981555_1_EIGVECS_0 implements java.io.Serializable {
    static final void fill(double[][] sa) {
      sa[0] = PCA_model_python_1462483981555_1_EIGVECS_0_0.VALUES;
      sa[1] = PCA_model_python_1462483981555_1_EIGVECS_0_1.VALUES;
      sa[2] = PCA_model_python_1462483981555_1_EIGVECS_0_2.VALUES;
      sa[3] = PCA_model_python_1462483981555_1_EIGVECS_0_3.VALUES;
    }
  }
}
// The class representing training column names
class NamesHolder_PCA_model_python_1462483981555_1 implements java.io.Serializable {
  public static final String[] VALUES = new String[2];
  static {
    NamesHolder_PCA_model_python_1462483981555_1_0.fill(VALUES);
  }
  static final class NamesHolder_PCA_model_python_1462483981555_1_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "account_type";
      sa[1] = "tbtw_skew";
    }
  }
}
// The class representing column account_type
class PCA_model_python_1462483981555_1_ColInfo_0 implements java.io.Serializable {
  public static final String[] VALUES = new String[3];
  static {
    PCA_model_python_1462483981555_1_ColInfo_0_0.fill(VALUES);
  }
  static final class PCA_model_python_1462483981555_1_ColInfo_0_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "Admin";
      sa[1] = "Service";
      sa[2] = "User";
    }
  }
}

