#!/bin/bash -ex
# we should always set proper ownership before exiting, otherwise
# the created packages will have root:root ownership and we'll be unable
# to delete them from our host.
trap 'chown -R --reference /build-inside/build-package /out/' EXIT

# the source directory is mounted read-only to prevent issues where the build
# could alter the source; we should copy it somewhere inside the container
cd /go/src/github.com/h2oai/steam
rsync -a /source/ .
make all linux rpm_package

cp /go/src/github.com/h2oai/steam/dist/*.rpm /out

