
// GENERATED BY crudgen; DON'T EDIT

package examples

import (
	"database/sql"
	"log"
	"time"

	"github.com/pkg/errors"
	"gopk.in/doug-martin/goqu.v3"
)

// ---------- -- ----------
// ---------- -- ----------
// ---------- Pk ----------
// ---------- -- ----------
// ---------- -- ----------

func (ds *Datastore) CreatePk(num int, name string, options ...func(*QueryConfig)) (int64, error) {
// Default insert fields
	pk := goqu.Record{ 
		"num": num,
		"name": name,
		"type_1": "normal",
		}
	// Setup query with optional parameters
	q := NewQueryConfig(ds.db.From("pk"), pk)
	for _, option := range options {
		option(q)
	}
	if DEBUG {
		log.Println(q.dataset.ToInsertSql(q.fields))
	}
	// Execut query
	res, err := q.dataset.Insert(q.fields).Exec()
	if err != nil {
		return 0, errors.Wrap(err, "executing query")
	}
	return res.LastInsertId()
}

