#!/bin/sh
set -e

#if [ "$1" = purge ]; then
#	rm -rf /var/run/uuidd
#fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d steam remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
# Hacked up manually.  This is probably wrong.
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask steam.service steam.socket >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge steam.service steam.socket >/dev/null
		deb-systemd-helper unmask steam.service steam.socket >/dev/null
	fi
fi
# End automatically added section

