title = "Steam Config File"

# Simple config file for steam laucher

[admin]
name = "admin"
password = "admin012"

[steam]
port = 9000

# Configurations for default roles
# More roles may be added using this format
#	[roles.{NAME}]
#	description = {DESCRIPTION}
# 	permissions = [{LIST OF PERMISSIONS}]

[roles]

	[roles.Admin]
	description = "Default admin role"
	permissions = [
		"ManageRole",
		"ViewRole",
		"ManageWorkgroup",
		"ViewWorkgroup",
		"ManageIdentity",
		"ViewIdentity",
		"ManageEngine",
		"ViewEngine",
		"ManageCluster",
		"ViewCluster",
		"ManageProject",
		"ViewProject",
		"ManageDatasource",
		"ViewDatasource",
		"ManageDataset",
		"ViewDataset",
		"ManageModel",
		"ViewModel",
		"ManageLabel",
		"ViewLabel",
		"ManageService",
		"ViewService"
	]

	[roles.ProjectLead]
	description = "Default project lead"
	permissions = [
		"ViewRole",
		"ManageWorkgroup",
		"ViewWorkgroup",
		"ViewIdentity",
		"ViewEngine",
		"ManageCluster",
		"ViewCluster",
		"ManageProject",
		"ViewProject",
		"ManageDatasource",
		"ViewDatasource",
		"ManageDataset",
		"ViewDataset",
		"ManageModel",
		"ViewModel",
		"ManageLabel",
		"ViewLabel",
		"ManageService",
		"ViewService"
	]

	[roles.DataScientist]
	description = "Default data scientist"
	permissions = [
		"ViewRole",
		"ViewWorkgroup",
		"ViewIdentity",
		"ViewEngine",
		"ViewCluster",
		"ViewProject",
		"ManageDatasource",
		"ViewDatasource",
		"ManageDataset",
		"ViewDataset",
		"ManageModel",
		"ViewModel",
		"ViewLabel",
		"ViewService"
	]

[predictionbuilder]
jettypath = "var/master/assets/jetty-runner.jar"
warpath = "var/master/assets/ROOT.war"
host = "localhost"
port = 8080


[predictionservice]
# host = "localhost" # Set to localhost to use without internet access
portrange = "1025:65535"
