# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "centos6.4"
    
  config.vm.provision :shell, 
    path:"setup.sh",
    env: {VERSION: "2.6.4"},
    privileged: true

  config.vm.network "forwarded_port", guest: 8088, host: 8088 # Yarn App Manageer Default
  # config.vm.network "forwarded_port", guest: 50070, host: 50070 # Namenode
  config.vm.network "forwarded_port", guest: 9000, host: 9000 # Steam Default
  config.vm.network :private_network, ip: "192.168.64.101"


  config.vm.synced_folder "../../../dist", "/steam"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "6144"
  end
end