# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-6.8"
    
  config.vm.provision :shell, 
    path:"setup.sh",
    env: {VERSION: "2.6.4"},
    privileged: true

  config.vm.network "forwarded_port", guest: 8088, host: 8088 # Yarn App Manager Default
  # config.vm.network "forwarded_port", guest: 50070, host: 50070 # Namenode
  config.vm.network "forwarded_port", guest: 9000, host: 9000 # Steam Default
  config.vm.network "forwarded_port", guest: 9001, host: 9001 # Steam Default
  config.vm.network "forwarded_port", guest: 9002, host: 9002 # Steam Default
  config.vm.network :private_network, ip: "192.168.64.101"

  # config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../../../../../..", "/home/vagrant/Go",
    owner: "vagrant", group: "vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "6144"
  end
end