#!/bin/sh

### BEGIN INIT INFO
# Provides:          steam
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: H2O Steam service
# Description:       H2O Steam service
#                    <...>
#                    <...>
### END INIT INFO

# Author: Steam Team <steam@h2o.ai>

PATH=/bin:/usr/bin:/sbin:/usr/sbin
H2ODIR=/opt/h2oai/steam
DAEMON=$H2ODIR/steam
STEAM_USER=steam
STEAM_GROUP=steam
PIDFILE=/var/run/steam.pid

. /etc/steam/steam.conf

case "$1" in
  set-admin)
    # Interactively prompt to set local steam admin username and password.
    $DAEMON --set-admin
    if [ $? -ne 0 ]; then
      echo "ERROR: setting admin credentials failed"
      exit 2
    fi
    ;;
  create-self-signed-cert)
    # Helper to get set up quickly if you don't have a real certificate from your IT department.
    openssl req -x509 -newkey rsa:4096 -keyout /etc/steam/private_key.pem -out /etc/steam/cert.pem -days 3650 -nodes -subj "/O=steam"
    if [ $? -ne 0 ]; then
      echo "ERROR: cert creation failed"
      exit 2
    fi
    ;;
  start)
    logger -s -p INFO "INFO: Starting H2O Steam..."

    pidof steam
    RC=$?
    if [ $RC -ne 1 ]; then
      logger -s -p ERR "ERROR: Steam is already running"
      exit 2
    fi

    if [ ! -f $STEAM_WEB_TLS_CERT_PATH ]; then
      logger -s -p ERR "ERROR: no cert ($STEAM_WEB_TLS_CERT_PATH)"
      echo ""
      echo "Try $0 create-self-signed-cert"
      exit 2
    fi

    if [ ! -f $STEAM_WEB_TLS_PRIVATE_KEY_PATH ]; then
      logger -s -p ERR "ERROR: no key ($STEAM_WEB_TLS_PRIVATE_KEY_PATH)"
      echo ""
      echo "Try $0 create-self-signed-cert"
      exit 2
    fi

    if [ `id -u` -ne 0 ]; then
      logger -s -p ERR "ERROR: Must be root"
      exit 2
    fi

    $DAEMON --check-admin
    if [ $? -ne 0 ]; then
      logger -s -p ERR "ERROR: no admin credentials set"
      echo ""
      echo "Try $0 set-admin"
      exit 2
    fi

    start-stop-daemon \
      --start \
      --make-pidfile --pidfile $PIDFILE \
      --background \
      --startas /bin/bash -- -c "exec $DAEMON serve master --web-address=:$STEAM_HTTPS_PORT --cluster-proxy-address=:$STEAM_PROXY_HTTPS_PORT --web-tls-cert-path=$STEAM_WEB_TLS_CERT_PATH --web-tls-key-path=$STEAM_WEB_TLS_PRIVATE_KEY_PATH --working-directory=$H2ODIR/var/master >> /var/log/steam.log 2>&1"

    RC=$?
    if [ $RC -ne 0 ]; then
      logger -s -p ERR "ERROR: Start failed (RC is $RC)"
      exit 2
    else
      logger -s -p INFO "INFO: Started with pid `cat $PIDFILE`"
    fi
    ;;
  stop)
    logger -s -p INFO "INFO: Stopping H2O Steam..."
    start-stop-daemon --oknodo --stop --pidfile $PIDFILE
    RC=$?
    if [ $RC -ne 0 ]; then
      logger -s -p WARN "WARN: Stop failed (RC is $RC), but ignoring"
    else
      rm -f $PIDFILE
      logger -s -p INFO "INFO: Stopped"
    fi
    ;;
  force-stop)
    logger -s -p INFO "INFO: Force stopping H2O Steam..."
    killall steam
    rm -f $PIDFILE
    logger -s -p INFO "INFO: Stopped"
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/steam {set-admin|start|stop|force-stop|restart|force-reload}"
    exit 1
    ;;
esac

exit 0
